/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#define main main__
#include "../../../lib/libfunc.c"
int libfunc_lib_libfunc_c(int a) {
return libfunc(a);
}
