/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#include "main_dot_c_test.h"

#include "gtest/gtest.h"
namespace UTBot {
static const float utbot_abs_error = 1e-6;


#pragma region error
TEST(error, main_test_1)
{
    char _argv[2][2] = {{'c', 'c'}, {'c', 'c'}};
    char ** argv = (char **) calloc(3, sizeof(char *));
    for (int it_6_0 = 0; it_6_0 < 2; it_6_0 ++) {
        argv[it_6_0] = _argv[it_6_0];
    }
    argv[2] = NULL;
    main(0, argv);
}

#pragma endregion
}
