/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#include "libfunc_dot_c_test.h"

#include "gtest/gtest.h"
namespace UTBot {
static const float utbot_abs_error = 1e-6;


#pragma region regression
TEST(regression, libfunc_test_1)
{
    int actual = libfunc(2);
    EXPECT_EQ(0, actual);
}

#pragma endregion
#pragma region error
TEST(error, libfunc_test_2)
{
    libfunc(0);
}

#pragma endregion
}
